## Appendix E: HTTP requests

Due to the nature of the interoperation of websites currently, often the easiest way to fetch data or other information is via HTTP requests, which is the backbone of the internet.  We will use the `HTTP` package here, which is incredibly powerful, including the ability to build a simple webserver, however, the point is this is to access information via web API requests. 

In [4]:
using HTTP,JSON

Here's a webserver that provides some simple API requests.  You may want to visit [http://httpbin.org](http:/httpbin.org) to see what it is capable of:

In [37]:
response = HTTP.request("GET","http://httpbin.org")

HTTP.Messages.Response:
"""
HTTP/1.1 200 OK
Date: Sun, 29 Nov 2020 22:02:32 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 9593
Connection: keep-alive
Server: gunicorn/19.9.0
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>httpbin.org</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Source+Code+Pro:300,600|Titillium+Web:400,600,700"
        rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/flasgger_static/swagger-ui.css">
    <link rel="icon" type="image/png" href="/static/favicon.ico" sizes="64x64 32x32 16x16" />
    <style>
        html {
            box-sizing: border-box;
            overflow: -moz-scrollbars-vertical;
            overflow-y: scroll;
        }

        *,
        *:before,
        *:after {
            box-sizing: inherit;
        }

        body {
            margin: 0;
            background: #fafafa;

The result is a: 

In [38]:
typeof(r)

HTTP.Messages.Response

Which stores the status, body, headers, 

In [39]:
r.status

200

This is the HTTP status of the response.  200 is normal

In [40]:
r.headers

7-element Array{Pair{SubString{String},SubString{String}},1}:
                             "Date" => "Sun, 29 Nov 2020 16:43:01 GMT"
                     "Content-Type" => "text/html; charset=utf-8"
                   "Content-Length" => "9593"
                       "Connection" => "keep-alive"
                           "Server" => "gunicorn/19.9.0"
      "Access-Control-Allow-Origin" => "*"
 "Access-Control-Allow-Credentials" => "true"

This has information about content type and other info.  The meat of this is in the `response.body`

In [41]:
response.body

9593-element Array{UInt8,1}:
 0x3c
 0x21
 0x44
 0x4f
 0x43
 0x54
 0x59
 0x50
 0x45
 0x20
 0x68
 0x74
 0x6d
    ⋮
 0x64
 0x79
 0x3e
 0x0a
 0x0a
 0x3c
 0x2f
 0x68
 0x74
 0x6d
 0x6c
 0x3e

which is quite unhelpful, until you turn this into a string:

In [42]:
String(response.body)

"<!DOCTYPE html>\n<html lang=\"en\">\n\n<head>\n    <meta charset=\"UTF-8\">\n    <title>httpbin.org</title>\n    <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:400,700|Source+Code+Pro:300,600|Titillium+Web:400,600,700\"\n        rel=\"stylesheet\">\n    <link rel=\"stylesheet\" type=\"text/css\" href=\"/flasgger_static/swagger-ui.css\">\n    <link rel=\"icon\" type=\"image/png\" href=\"/static/favicon.ico\" sizes=\"64x64 32x32 16x16\" />\n    <style>\n        html {\n            box-sizing: border-box;\n            overflow: -moz-scrollbars-vertical;\n            overflow-y: scroll;\n        }\n\n        *,\n        *:before,\n        *:after {\n            box-sizing: inherit;\n        }\n\n        body {\n            margin: 0;\n            background: #fafafa;\n        }\n    </style>\n</head>\n\n<body>\n    <a href=\"https://github.com/requests/httpbin\" class=\"github-corner\" aria-label=\"View source on Github\">\n        <svg width=\"80\" height=\"80\" viewBox=\

this is standard HTML, which you could save and then load in a browers (and there may be a way to do this in jupyter lab). 

However, a more interesting idea with this website is to get information from the webserver.  

In [43]:
req1 = HTTP.request("GET","https://httpbin.org/get")

HTTP.Messages.Response:
"""
HTTP/1.1 200 OK
Date: Sun, 29 Nov 2020 22:02:43 GMT
Content-Type: application/json
Content-Length: 264
Connection: keep-alive
Server: gunicorn/19.9.0
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true

{
  "args": {}, 
  "headers": {
    "Content-Length": "0", 
    "Host": "httpbin.org", 
    "User-Agent": "HTTP.jl/1.5.3", 
    "X-Amzn-Trace-Id": "Root=1-5fc41a83-376899777bd8e1035c195b27"
  }, 
  "origin": "141.154.51.251", 
  "url": "https://httpbin.org/get"
}
"""

Notice that this time, the `Content-Type` is `application/json`, which is more helpful to programmatically use

In [44]:
body1 = String(req1.body)

"{\n  \"args\": {}, \n  \"headers\": {\n    \"Content-Length\": \"0\", \n    \"Host\": \"httpbin.org\", \n    \"User-Agent\": \"HTTP.jl/1.5.3\", \n    \"X-Amzn-Trace-Id\": \"Root=1-5fc41a83-376899777bd8e1035c195b27\"\n  }, \n  \"origin\": \"141.154.51.251\", \n  \"url\": \"https://httpbin.org/get\"\n}\n"

which can be parsed:

In [45]:
JSON.parse(body1)

Dict{String,Any} with 4 entries:
  "headers" => Dict{String,Any}("Content-Length"=>"0","Host"=>"httpbin.org","Us…
  "args"    => Dict{String,Any}()
  "url"     => "https://httpbin.org/get"
  "origin"  => "141.154.51.251"

In [46]:
req2 = HTTP.request("GET","https://httpbin.org/base64/SFRUUEJJTiBpcyBhd2Vzb21l")

HTTP.Messages.Response:
"""
HTTP/1.1 200 OK
Date: Sun, 29 Nov 2020 22:02:50 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 18
Connection: keep-alive
Server: gunicorn/19.9.0
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true

HTTPBIN is awesome"""

In [47]:
String(req2.body)

"HTTPBIN is awesome"

Let's use a `POST` to the server:

In [59]:
req3 = HTTP.request("POST","https://httpbin.org/anything",[],"{msg: \"hi\"}")

HTTP.Messages.Response:
"""
HTTP/1.1 200 OK
Date: Sun, 29 Nov 2020 22:06:24 GMT
Content-Type: application/json
Content-Length: 367
Connection: keep-alive
Server: gunicorn/19.9.0
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true

{
  "args": {}, 
  "data": "{msg: \"hi\"}", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Content-Length": "11", 
    "Host": "httpbin.org", 
    "User-Agent": "HTTP.jl/1.5.3", 
    "X-Amzn-Trace-Id": "Root=1-5fc41b60-57b7b76e74f2a5df0dd6c98b"
  }, 
  "json": null, 
  "method": "POST", 
  "origin": "141.154.51.251", 
  "url": "https://httpbin.org/anything"
}
"""

In [60]:
JSON.parse(String(req3.body))

Dict{String,Any} with 9 entries:
  "headers" => Dict{String,Any}("Content-Length"=>"11","Host"=>"httpbin.org","U…
  "json"    => nothing
  "method"  => "POST"
  "files"   => Dict{String,Any}()
  "args"    => Dict{String,Any}()
  "data"    => "{msg: \"hi\"}"
  "url"     => "https://httpbin.org/anything"
  "form"    => Dict{String,Any}()
  "origin"  => "141.154.51.251"

### Mapquest API

In the next homework, we are going to find the shortest distance between a set of towns.  Although it's not difficult to type everything into google maps (or something equivalent), it's tedious.  Instead we are going to use the mapquest API to grab data.

First, you'll need to go to [https://developer.mapquest.com](https://developer.mapquest.com) and sign up for a key.  It's quite easy. Go do it!

In [18]:
mapquest_key = "WL9lkNndull1hszCbog4MicH6ZRPGEEO" ## add your key here. 

"WL9lkNndull1hszCbog4MicH6ZRPGEEO"

Let's test with with a request to get an optimized route from Fitchburg to Boston.

In [19]:
mapquest = HTTP.request("GET",string("http://open.mapquestapi.com/directions/v2/optimizedroute",
    "?key=$mapquest_key&from=Fitchburg,MA&to=Boston,MA"))

HTTP.Messages.Response:
"""
HTTP/1.1 200 OK
Date: Sun, 29 Nov 2020 22:16:45 GMT
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Server: Apache-Coyote/1.1
Set-Cookie: JSESSIONID=252FEED8ED5EF0BD4C9C4EFF3EB25397; Path=/directions; HttpOnly
Expires: Mon, 20 Dec 1998 01:00:00 GMT
Last-Modified: Sun, 29 Nov 2020 22:16:45 GMT
Cache-Control: no-cache, must-revalidate
Pragma: no-cache
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS,GET,POST
status: success
transactionWeight: 1

{"route":{"hasTollRoad":false,"hasBridge":false,"boundingBox":{"lr":{"lng":-71.057327,"lat":42.360317},"ul":{"lng":-71.804382,"lat":42.584591}},"distance":47.345,"hasTimedRestriction":false,"hasTunnel":true,"hasHighway":true,"computedWaypoints":[],"routeError":{"errorCode":-400,"message":""},"formattedTime":"01:02:50","sessionId":"5fc41dcd-01b8-4ee4-02b4-350f-0af15b1a365b","hasAccessRestriction":false,"realTime":-1,"hasSeasonalClosure":false,"hasCountry

In [20]:
route = JSON.parse(String(mapquest.body))

Dict{String,Any} with 2 entries:
  "route" => Dict{String,Any}("hasCountryCross"=>false,"legs"=>Any[Dict{String,…
  "info"  => Dict{String,Any}("messages"=>Any[],"statuscode"=>0,"copyright"=>Di…

In [22]:
route["info"]

Dict{String,Any} with 3 entries:
  "messages"   => Any[]
  "statuscode" => 0
  "copyright"  => Dict{String,Any}("imageUrl"=>"http://api.mqcdn.com/res/mqlogo…

In [8]:
route["route"]

Dict{String,Any} with 23 entries:
  "hasCountryCross"      => false
  "legs"                 => Any[Dict{String,Any}("hasCountryCross"=>false,"road…
  "hasUnpaved"           => false
  "time"                 => 3770
  "formattedTime"        => "01:02:50"
  "hasTimedRestriction"  => false
  "locations"            => Any[Dict{String,Any}("latLng"=>Dict{String,Any}("la…
  "distance"             => 47.345
  "boundingBox"          => Dict{String,Any}("ul"=>Dict{String,Any}("lat"=>42.5…
  "hasBridge"            => false
  "hasTollRoad"          => false
  "locationSequence"     => Any[0, 1]
  "computedWaypoints"    => Any[]
  "hasAccessRestriction" => false
  "hasFerry"             => false
  "realTime"             => -1
  "options"              => Dict{String,Any}("doReverseGeocode"=>true,"routeTyp…
  "routeError"           => Dict{String,Any}("errorCode"=>-400,"message"=>"")
  "sessionId"            => "5fc41c91-0230-4ee4-02b4-3505-12a32283d7e3"
  "fuelUsed"             => 1.82
  "hasSeaso

In [9]:
route["route"]["distance"]

47.345

In [24]:
route["route"]["legs"]

1-element Array{Any,1}:
 Dict{String,Any}("hasCountryCross" => false,"roadGradeStrategy" => Any[Any[]],"origIndex" => -1,"hasUnpaved" => false,"time" => 3770,"formattedTime" => "01:02:50","destNarrative" => "","hasTimedRestriction" => false,"origNarrative" => "","distance" => 47.345…)

Let's find all distances between the following:  Fitchburg, MA; Boston, MA; Providence, RI; Nashua, NH; Portland, ME; Concord, NH;

We need to build up a Dictionary with this info.  The `locations` field is an array of all of the towns and the `options` field needs to say that `allToAll` is true so we get all pairs of distances. 

In [26]:
towns = Dict(
    "locations"=>["Fitchburg, MA","Boston, MA","Providence, RI","Nashua, NH","Portland, ME", "Concord, NH"],
      "options" => Dict("allToAll"=>true))

Dict{String,Any} with 2 entries:
  "locations" => ["Fitchburg, MA", "Boston, MA", "Providence, RI", "Nashua, NH"…
  "options"   => Dict{String,Bool}("allToAll"=>1)

Then we encode the dictionary as a JSON string. 

In [31]:
towns_json = JSON.json(towns)

"{\"locations\":[\"Fitchburg, MA\",\"Boston, MA\",\"Providence, RI\",\"Nashua, NH\",\"Portland, ME\",\"Concord, NH\"],\"options\":{\"allToAll\":true}}"

And this is how the request is made:

In [40]:
req2 = HTTP.request("POST","http://www.mapquestapi.com/directions/v2/routematrix?key=$mapquest_key",[],towns_json)

HTTP.Messages.Response:
"""
HTTP/1.1 200 OK
Date: Sun, 29 Nov 2020 22:26:04 GMT
Content-Type: application/json;charset=UTF-8
Content-Length: 3286
Server: Apache-Coyote/1.1
Set-Cookie: JSESSIONID=C3151EBC5D4281B68E5AD91F8C6EAEEB; Path=/directions; HttpOnly
Expires: Mon, 20 Dec 1998 01:00:00 GMT
Last-Modified: Sun, 29 Nov 2020 22:26:04 GMT
Cache-Control: no-cache, must-revalidate
Pragma: no-cache
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS,GET,POST
status: success
transactionWeight: 1

{"allToAll":true,"distance":[[0,60.021,65.674,25.147,128.19,56.42],[59.763,0,49.944,42.669,112.144,67.425],[65.043,49.971,0,86.956,173.397,116.723],[25.038,43.067,86.786,0,106.094,34.973],[127.789,107.307,162.937,105.83,0,109.159],[55.454,67.698,117.997,35.188,109.835,0]],"locations":[{"dragPoint":false,"displayLatLng":{"lng":-71.795967,"lat":42.580807},"adminArea4":"Worcester County","adminArea5":"Fitchburg","postalCode":"","adminArea1":"US","adminArea3":"MA","type":"s","sideOfStr

The result is in the body field and needs to be parsed as a JSON. The distance information is in the `distance` field.

In [41]:
distance_dict = JSON.parse(String(req2.body))

Dict{String,Any} with 6 entries:
  "locations" => Any[Dict{String,Any}("latLng"=>Dict{String,Any}("lat"=>42.5808…
  "distance"  => Any[Any[0, 60.021, 65.674, 25.147, 128.19, 56.42], Any[59.763,…
  "time"      => Any[Any[0, 3856, 4396, 2613, 7536, 4340], Any[3806, 0, 3204, 3…
  "allToAll"  => true
  "info"      => Dict{String,Any}("messages"=>Any[],"statuscode"=>0,"copyright"…
  "manyToOne" => false

In [42]:
A=distance_dict["distance"]

6-element Array{Any,1}:
 Any[0, 60.021, 65.674, 25.147, 128.19, 56.42]
 Any[59.763, 0, 49.944, 42.669, 112.144, 67.425]
 Any[65.043, 49.971, 0, 86.956, 173.397, 116.723]
 Any[25.038, 43.067, 86.786, 0, 106.094, 34.973]
 Any[127.789, 107.307, 162.937, 105.83, 0, 109.159]
 Any[55.454, 67.698, 117.997, 35.188, 109.835, 0]

And we can do the following to turn it into a 2D array, which will be easier to handle.

In [43]:
dist_array = collect(transpose(reshape(collect(Iterators.flatten(A)),(6,6))))

6×6 Array{Real,2}:
   0       60.021   65.674   25.147  128.19    56.42
  59.763    0       49.944   42.669  112.144   67.425
  65.043   49.971    0       86.956  173.397  116.723
  25.038   43.067   86.786    0      106.094   34.973
 127.789  107.307  162.937  105.83     0      109.159
  55.454   67.698  117.997   35.188  109.835    0