## Appendix B: 

In [3]:
bitstring(Int8(18))

"00010010"

In [6]:
bitstring(Int8(-1))

"11111111"

In [11]:
parse(Int8,"11111111",base = 2)

OverflowError: OverflowError: overflow parsing "11111111"

In [12]:
0b1111111

0x7f

In [16]:
Int8(0b11111111)

InexactError: InexactError: check_top_bit(Int8, 255)

In [19]:
bitstring(Int8(-128))

"10000000"

In [20]:
bitstring(UInt8(255))

"11111111"

In [24]:
bitstring(Int8(1))

"00000001"

In [27]:
bitstring(Int8(-41))

"11010111"

In [1]:
function dec2bin(n::Int)
  bdigits=zeros(Bool,8)
  ## this function calclates the digit of the decimal number k that goes in slot digit
  function calcDigit(k::Int,digit::Int)
    if digit==0
      bdigits[1] = k
    else 
      bdigits[digit+1] = div(k,2^digit)
      calcDigit(mod(k,2^digit),digit-1)
    end
  end
  calcDigit(n,6)
  bdigits
end

dec2bin (generic function with 1 method)

In [2]:
dec2bin(47)

8-element Array{Bool,1}:
 1
 1
 1
 1
 0
 1
 0
 0

In [3]:
bitstring(Int8(54))

"00110110"

In [4]:
bitstring(Int8(19))

"00010011"

In [5]:
function dec2bin(n::Int)
  bdigits=zeros(Bool,8)
  ## this function calclates the digit of the decimal number k that goes in slot digit
  function calcDigit(k::Int,digit::Int)
    if digit==0
      bdigits[1] = k
    else 
      bdigits[digit+1] = div(k,2^digit)
      calcDigit(mod(k,2^digit),digit-1)
    end
  end
  if n>=0 
    calcDigit(n,6)
  else 
    calcDigit(128+n,6)
    bdigits[8]=1
  end
  bdigits
end

dec2bin (generic function with 1 method)

In [6]:
dec2bin(-67)

8-element Array{Bool,1}:
 1
 0
 1
 1
 1
 1
 0
 1

In [7]:
## this function takes a 0-1 array (boolean array) and changes it to a decimal. 
# the first element is the 2^0 digits, the 7th digit is the 2^6 digit and the 8th digit is the sign digit
# this uses the 2's complement representation
#
function bin2dec(arr::Array{Bool,1})
  sum=0
  for i=1:7
    sum += arr[i]*2^(i-1)
  end
  sum - arr[8]*128
end

bin2dec (generic function with 1 method)

In [8]:
bin2dec(map(x->convert(Bool,x),[1,0,1,0,1,0,1,1]))

-43

In [9]:
bin2dec(dec2bin(-67))

-67

In [10]:
dec2bin(-67) |> reverse |> arr -> reduce((x, y)->string(x,y ? "1" : "0"),arr,init="")

"10111101"

In [11]:
reverse([1,2,3])

3-element Array{Int64,1}:
 3
 2
 1

In [12]:
"10111101" |> str->split(str,"") |> arr-> map(x-> x=="1" ? true : false, arr) |> reverse 

8-element Array{Bool,1}:
 1
 0
 1
 1
 1
 1
 0
 1

In [13]:
arr2str(arr::Array{Bool,1}) = reduce((x, y)->string(x,y ? "1" : "0"),reverse(arr),init="")

arr2str (generic function with 1 method)

In [14]:
dec2bin(-67) |> arr2str

"10111101"

In [15]:
str2arr(str::String) = reverse(map(x-> x=="1" ? true : false, split(str,"")))

str2arr (generic function with 1 method)

In [16]:
bin2dec(str2arr("10111101"))

-67

In [17]:
bin2dec(str2arr("01001100"))

76

In [18]:
bin2dec(str2arr("01100010"))

98

In [19]:
76+98

174

In [20]:
bitstring(Int16(174))

"0000000010101110"

In [21]:
bitstring(Int8(10)),bitstring(Int8(11))

("00001010", "00001011")

In [22]:
bitstring(Int8(-10)),bitstring(Int8(-11))

("11110110", "11110101")

In [26]:
bin2dec(str2arr("10101010"))

-86

In [29]:
bin2dec(str2arr("10000000"))

-128

In [30]:
bin2dec(str2arr("01111111"))

127

In [31]:
bin2dec(str2arr("10000000"))

-128

In [32]:
x=Int8(-128)

-128

In [33]:
-x

-128

In [42]:
bitstring(0.1)

"0011111110111001100110011001100110011001100110011001100110011010"

In [39]:
bitstring(1/3)

"0011111111010101010101010101010101010101010101010101010101010101"

In [41]:
1/3+2/3

1.0

In [1]:
Base.checked_add(UInt8())

MethodError: MethodError: no method matching UInt8()
Closest candidates are:
  UInt8(!Matched::Union{Bool, Int32, Int64, UInt32, UInt64, UInt8, Int128, Int16, Int8, UInt128, UInt16}) at boot.jl:710
  UInt8(!Matched::Float32) at float.jl:685
  UInt8(!Matched::Float64) at float.jl:685
  ...

In [5]:
1/9+1/9+1/9+1/9+1/9+1/9+1/9+1/9+1/9

1.0000000000000002

In [8]:
1/10+1/10+1/10+1/10+1/10+1/10+1/10+1/10+1/10+1/10

0.9999999999999999

In [9]:
[10^i for i=10:20]

11-element Array{Int64,1}:
          10000000000
         100000000000
        1000000000000
       10000000000000
      100000000000000
     1000000000000000
    10000000000000000
   100000000000000000
  1000000000000000000
 -8446744073709551616
  7766279631452241920

In [10]:
[10^i for i=21:35]

15-element Array{Int64,1}:
  3875820019684212736
  1864712049423024128
   200376420520689664
  2003764205206896640
  1590897978359414784
 -2537764290115403776
 -6930898827444486144
  4477988020393345024
  7886392056514347008
  5076944270305263616
 -4570789518076018688
 -8814407033341083648
  4089650035136921600
  4003012203950112768
  3136633892082024448

In [11]:
[10^i for i=36:50]

15-element Array{Int64,1}:
 -5527149226598858752
    68739955140067328
   687399551400673280
  6873995514006732800
 -5047021154770878464
  4870020673419870208
 -6640025486929952768
  7386721425538678784
    80237960548581376
   802379605485813760
  8023796054858137600
  6450984253743169536
  9169610316303040512
  -537617205517352960
 -5376172055173529600

In [12]:
[10^i for i=51:70]

20-element Array{Int64,1}:
  1578511669393358848
 -2661627379775963136
 -8169529724050079744
 -7908320945662590976
 -5296233161787703296
  2377900603251621888
  5332261958806667264
 -2017612633061982208
 -1729382256910270464
  1152921504606846976
 -6917529027641081856
  4611686018427387904
 -9223372036854775808
                    0
                    0
                    0
                    0
                    0
                    0
                    0

In [13]:
typeof(BigInt(10))

BigInt

In [14]:
big(1/9)

0.111111111111111104943205418749130330979824066162109375

In [16]:
a=big(1)/big(9)

0.1111111111111111111111111111111111111111111111111111111111111111111111111111109

In [18]:
setprecision(2^10)

1024

In [19]:
a1=big(1)/big(9)

0.111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111

In [20]:
Float16(1)/Float16(9)

Float16(0.1111)

In [23]:
typemax(Float16)

Inf16

In [39]:
[2.0^i for i=1000:1030]

31-element Array{Float64,1}:
  1.0715086071862673e301
  2.1430172143725346e301
  4.2860344287450693e301
  8.572068857490139e301
  1.7144137714980277e302
  3.4288275429960554e302
  6.857655085992111e302
  1.3715310171984222e303
  2.7430620343968443e303
  5.486124068793689e303
  1.0972248137587377e304
  2.1944496275174755e304
  4.388899255034951e304
  ⋮
  5.617791046444737e306
  1.1235582092889474e307
  2.247116418577895e307
  4.49423283715579e307
  8.98846567431158e307
 Inf
 Inf
 Inf
 Inf
 Inf
 Inf
 Inf

In [40]:
tup=(1,2,3,4)

(1, 2, 3, 4)

In [41]:
tup[1]

1

In [42]:
tup[3]=9

MethodError: MethodError: no method matching setindex!(::NTuple{4,Int64}, ::Int64, ::Int64)

In [47]:
pt1=(x=1,y=3.2,z=9)

(x = 1, y = 3.2, z = 9)

In [48]:
pt.x

1

In [49]:
pt2=(x=4,y=5,z=0.1)

(x = 4, y = 5, z = 0.1)

In [50]:
pt1+pt2

MethodError: MethodError: no method matching +(::NamedTuple{(:x, :y, :z),Tuple{Int64,Float64,Int64}}, ::NamedTuple{(:x, :y, :z),Tuple{Int64,Int64,Float64}})
Closest candidates are:
  +(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:538

### Rational Numbers

In [2]:
2//3
4//7
178//11
-1//2

-1//2

In [3]:
typeof(1//2)

Rational{Int64}

In [4]:
typeof(Int16(1)//Int16(2))

Rational{Int16}

In [9]:
sum(i->1//i,1:50)

LoadError: OverflowError: 5943339269060627227 * 47 overflowed for type Int64