## Chapter 6: Arrays

In [1]:
arr = [1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

In [2]:
length(arr)

3

In [3]:
eltype(arr)

Int64

### 6.1: Constructing Arrays

In [4]:
arr = [1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

In [6]:
arr2 = [1 2 3; 4 5 6]

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

In [7]:
zeros(Integer,4,6)

4×6 Array{Integer,2}:
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0

In [8]:
collect(1:10)

10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

### 6.2: Comprehensions

In [9]:
[(-1)^n for n=0:7]

8-element Array{Int64,1}:
  1
 -1
  1
 -1
  1
 -1
  1
 -1

In [10]:
[m+n for n=1:8,m=1:8]

8×8 Array{Int64,2}:
 2   3   4   5   6   7   8   9
 3   4   5   6   7   8   9  10
 4   5   6   7   8   9  10  11
 5   6   7   8   9  10  11  12
 6   7   8   9  10  11  12  13
 7   8   9  10  11  12  13  14
 8   9  10  11  12  13  14  15
 9  10  11  12  13  14  15  16

In [10]:
[n*2-m for n=1:5,m=1:6]

5×6 Array{Int64,2}:
 1  0  -1  -2  -3  -4
 3  2   1   0  -1  -2
 5  4   3   2   1   0
 7  6   5   4   3   2
 9  8   7   6   5   4

### 6.3: Accessing elements of an array

In [15]:
x = collect(1:2:13)

7-element Array{Int64,1}:
  1
  3
  5
  7
  9
 11
 13

In [16]:
x[2]

3

In [17]:
x[3:5]

3-element Array{Int64,1}:
 5
 7
 9

In [18]:
x[end-2:end]

3-element Array{Int64,1}:
  9
 11
 13

In [19]:
A=[i+j for i=1:4,j=1:5]

4×5 Array{Int64,2}:
 2  3  4  5  6
 3  4  5  6  7
 4  5  6  7  8
 5  6  7  8  9

In [20]:
A[:,1:2:5]

4×3 Array{Int64,2}:
 2  4  6
 3  5  7
 4  6  8
 5  7  9

In [21]:
A[1:2,[5,3,2]]

2×3 Array{Int64,2}:
 6  4  3
 7  5  4

### 6.4: Common Operations on Arrays

In [22]:
A=[1 2 3; 4 5 6]

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

In [23]:
B=[1 3 5; 2 4 6]

2×3 Array{Int64,2}:
 1  3  5
 2  4  6

In [24]:
A+B

2×3 Array{Int64,2}:
 2  5   8
 6  9  12

In [26]:
B-A

2×3 Array{Int64,2}:
  0   1  2
 -2  -1  0

### 6.5: Element by Element Operations

In [27]:
A.*B

2×3 Array{Int64,2}:
 1   6  15
 8  20  36

In [28]:
sqrt.(A)

2×3 Array{Float64,2}:
 1.0  1.41421  1.73205
 2.0  2.23607  2.44949

### 6.6: Other Operations on Arrays

In [29]:
sum(1:10)

55

In [30]:
prod([1,3,5,7])

105

### 6.7: Sorting Vectors and matrices

In [33]:
A=[3,2,1,4,8,6,5]

7-element Array{Int64,1}:
 3
 2
 1
 4
 8
 6
 5

In [34]:
sort(A)

7-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6
 8

In [35]:
sort(A,rev=true)

7-element Array{Int64,1}:
 8
 6
 5
 4
 3
 2
 1

### 6.8: Push and Pop; Array as a Stack

In [36]:
A=collect(1:5)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [37]:
push!(A,7)

6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 7

In [38]:
push!(A,8,9,10,100)

10-element Array{Int64,1}:
   1
   2
   3
   4
   5
   7
   8
   9
  10
 100

In [39]:
A=collect(1:5)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [40]:
pop!(A)

5

In [41]:
A

4-element Array{Int64,1}:
 1
 2
 3
 4

### 6.9: Other Nice Array Functions

In [42]:
A=[1,2,3]
append!(A,[4,5,6])

6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6

In [43]:
A=collect(1:2:11)

6-element Array{Int64,1}:
  1
  3
  5
  7
  9
 11

In [44]:
insert!(A,3,15)

7-element Array{Int64,1}:
  1
  3
 15
  5
  7
  9
 11

In [45]:
A=collect(1:2:11)

6-element Array{Int64,1}:
  1
  3
  5
  7
  9
 11

In [47]:
deleteat!(A,2)

5-element Array{Int64,1}:
  1
  5
  7
  9
 11

In [48]:
A=collect(1:2:13)

7-element Array{Int64,1}:
  1
  3
  5
  7
  9
 11
 13

In [49]:
splice!(A,3:4)

2-element Array{Int64,1}:
 5
 7

In [50]:
A

5-element Array{Int64,1}:
  1
  3
  9
 11
 13

In [52]:
A=collect(1:2:11)

6-element Array{Int64,1}:
  1
  3
  5
  7
  9
 11

In [53]:
x = splice!(A,2)

3

In [54]:
A

5-element Array{Int64,1}:
  1
  5
  7
  9
 11

In [55]:
A = collect(1:2:11)

6-element Array{Int64,1}:
  1
  3
  5
  7
  9
 11

In [56]:
 B=splice!(A,3:2,[11,12,13,14])

Int64[]

In [57]:
A

10-element Array{Int64,1}:
  1
  3
 11
 12
 13
 14
  5
  7
  9
 11

In [58]:
A = collect(1:2:11)

6-element Array{Int64,1}:
  1
  3
  5
  7
  9
 11

In [59]:
x = splice!(A,3,4)

5

In [60]:
A

6-element Array{Int64,1}:
  1
  3
  4
  7
  9
 11

In [61]:
A = collect(1:2:11)

6-element Array{Int64,1}:
  1
  3
  5
  7
  9
 11

In [62]:
splice!(A,3,[-1,-2,-3])

5

In [63]:
A

8-element Array{Int64,1}:
  1
  3
 -1
 -2
 -3
  7
  9
 11

In [64]:
A = collect(1:20)

20-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20

In [65]:
filter(n->n%2==0,A)

10-element Array{Int64,1}:
  2
  4
  6
  8
 10
 12
 14
 16
 18
 20

In [66]:
A=[1,2,3,2,3,4,3,4,5,4,3,2,1]

13-element Array{Int64,1}:
 1
 2
 3
 2
 3
 4
 3
 4
 5
 4
 3
 2
 1

In [67]:
unique(A)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5